### ISSUE TITLE
vpcpeering should support project name

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud/ansible-collection-cloud#107]
Getting project inside same domain is possible. Listing foreign projects is not possible in OTC, so for that ID must be passed. But if we can resolve - we should.

Summary: it should be possible to pass both local and remote router and project name into the module. It should try the best to resolve name to id and raise error if it is not capable. It is definitely possible to resolve local router/project. For remote it is only really possible if those are in the same project

**Comment by Polina-Gubina** [comment]
fixed in VPC peering fix #109
