### ISSUE TITLE
Create DDS instance module

### ISSUE THREAD

**Issue by anton-sidelnikov** [opentelekomcloud/ansible-collection-cloud#134]
according: https://docs.otc.t-systems.com/en-us/api/dds/dds_api_0020.html
please use cloud layer in python-otcextensions https://github.com/opentelekomcloud/python-otcextensions/blob/master/otcextensions/sdk/cloud/dds.py

**Comment by anton-sidelnikov** [comment]
and please add integration test

**Comment by enrrou** [comment]
feature was merged into master. issue resolved
