### ISSUE TITLE
Problems with opentelekomcloud.cloud.dns_zone 

### ISSUE THREAD

**Issue by hadoopch** [opentelekomcloud/ansible-collection-cloud#176]
Hi all,
today i tried to use this module.  It seems t be not idempotent. If i run this module twice i get the following error:

*fatal: [localhost]: FAILED! => {"changed": false, "extra_data": {"data": null, "details": "This VPC has already been associated with the zone. Zone ID:2c96b0fe7d8eb06c017f0cc21e0d598c.", "response": "{\"code\":\"DNS.0212\",\"message\":\"This VPC has already been associated with the zone. Zone ID:2c96b0fe7d8eb06c017f0cc21e0d598c.\"}"}, "msg": "This VPC has already been associated with the zone. Zone ID:2c96b0fe7d8eb06c017f0cc21e0d598c...*

I am using:

* ansible==2.9.0
* opentelekomcloud.cloud  "version": "0.11.0"

Kind regards
Uli

**Comment by enrrou** [comment]
Hello!
 Could you share playbook you run, please?

**Comment by hadoopch** [comment]
Hi Vladimir,

also the behaviour of  opentelekomcloud.cloud.vpc is unusual. 
Status is always changed. In the second run it should be OK.

Regards
Uli

```
TASK [sshmgmt-is : Create VPC 10.1.0.0/16 environment internal] *************************************************************************************************************************************************************************************************************************************************************
changed: [localhost]
```

**Comment by enrrou** [comment]
@hadoopch 
Thanks for your feedback.
I confirm the issue.
I'll let you know as soon as I find a solution.

**Comment by hadoopch** [comment]
@enrrou, 
thanks a lot !!!
Best regards
Uli

**Comment by enrrou** [comment]
Issue is fixed and soon fix will be published with next release

**Comment by hadoopch** [comment]
Thanks a lot.

**Comment by enrrou** [comment]
@hadoopch,
Try on newer release 0.12.0, please. That's must be working.
Waiting for your feedback.

**Comment by hadoopch** [comment]
Hi Vladimir,
today i tried  Creation of zones and VPC. Both is now working fine.
Thanks a lot.

Regards

Uli

**Comment by hadoopch** [comment]
Working with latest release

**Comment by enrrou** [comment]
Thanks for your feedback!
