### ISSUE TITLE
Hide sensitive data (password) in module's output

### ISSUE THREAD

**Issue by YustinaKvr** [opentelekomcloud/ansible-collection-cloud#219]
When you create a CSS cluster via https://github.com/opentelekomcloud/ansible-collection-cloud/blob/master/plugins/modules/css_cluster.py and setting db password, it shows in Ansible output as an open text.
For security reasons it need to be hide.

**Comment by vladimirvshivkov** [comment]
just add ` no_log: true` in your playbook

**Comment by YustinaKvr** [comment]
Yes, it can help, but only in my current case. And this option will not fix the whole issue, it will fix only the symptom. I think it's better to fix module's code to avoid security leak caused by user's oversight :)

**Comment by vladimirvshivkov** [comment]
how?

**Comment by YustinaKvr** [comment]
Like it was solved in other our module using 'password' field. Don't worry, I'm working on it

**Comment by vladimirvshivkov** [comment]
like this? https://github.com/opentelekomcloud/ansible-collection-cloud/pull/218/commits/91ce67f0d989087cfd7a441363598e5a879879e3

**Comment by YustinaKvr** [comment]
No, your commit related with backupStrategy errors, and mine - with password
