### ISSUE TITLE
Incompatible openstacksdk library found: Version MUST be >=0.36 and <=0.98.999, but 0.102.0 is larger than maximum version 0.98.999

### ISSUE THREAD

**Issue by martpeli** [opentelekomcloud/ansible-collection-cloud#233]
Hello,

i've installed ansible on Ubuntu 20.04 (in OTC) following your guide at:
https://github.com/opentelekomcloud/ansible-collection-cloud

checking the installation with your example ansible-playbook opentelekomcloud.yaml works well.
TASK [debug configs] ******************************************************************************************************************************************************
ok: [localhost] => {
    "gw.nat_gateways": [
        {
            "admin_state_up": true,
            "created_at": "2022-11-10 07:46:31.852232",
            "description": "",
            "id": "16d5a613-2122-4afc-a3aa-cd88aef77f6d",
            "internal_network_id": "54b43c321-3adf-4743-ba86-35e06b733150",
            "name": "nat-gw-pwc-ipaas",
            "project_id": "f1679e59b6c4357c8e13ce972e7c3a863",
            "router_id": "b0613b7d-da0d-4959-bdd7-d699a521903c4",
            "spec": "1",
            "status": "ACTIVE"
        }
    ]
}

Trying to install an ecs VM (with the openstack.cloud.server mdule), I get the following error:

TASK [Create ECS and attach it to the resources] *******************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Incompatible openstacksdk library found: Version MUST be >=0.36 and <=0.98.999, but 0.102.0 is larger than maximum version 0.98.999."}

The latest ansible doc of the openstack.cloud.server module specifies the following requirements:
openstacksdk >= 0.36, < 0.99.0
https://docs.ansible.com/ansible/latest/collections/openstack/cloud/server_module.html

pip list
...
openstacksdk       0.102.0

Downgrading the openstacksdk to version 0.61.0 gets my VM installation working (pip install openstacksdk==0.61.0)

but then running the opentelekomcloud.yaml example, I get the error:
"ModuleNotFoundError: No module named 'openstack.common'"

TASK [opentelekomcloud.cloud.dns_recordset - Creating / Updating a recordset] *********************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'openstack.common'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1668167141.7369413-17035-73944589752089/AnsiballZ_dns_recordset.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1668167141.7369413-17035-73944589752089/AnsiballZ_dns_recordset.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1668167141.7369413-17035-73944589752089/AnsiballZ_dns_recordset.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.opentelekomcloud.cloud.plugins.modules.dns_recordset', init_globals=dict(_module_fqn='ansible_collections.opentelekomcloud.cloud.plugins.modules.dns_recordset', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_opentelekomcloud.cloud.dns_recordset_payload_znmk3fn7/ansible_opentelekomcloud.cloud.dns_recordset_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/dns_recordset.py\", line 235, in <module>\n  File \"/tmp/ansible_opentelekomcloud.cloud.dns_recordset_payload_znmk3fn7/ansible_opentelekomcloud.cloud.dns_recordset_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/dns_recordset.py\", line 230, in main\n  File \"/tmp/ansible_opentelekomcloud.cloud.dns_recordset_payload_znmk3fn7/ansible_opentelekomcloud.cloud.dns_recordset_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/module_utils/otc.py\", line 97, in __init__\n  File \"/tmp/ansible_opentelekomcloud.cloud.dns_recordset_payload_znmk3fn7/ansible_opentelekomcloud.cloud.dns_recordset_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/module_utils/otc.py\", line 166, in openstack_cloud_from_module\n  File \"/home/ubuntu/ansiblevenv/lib/python3.8/site-packages/otcextensions/sdk/__init__.py\", line 357, in load\n    register_single_service(conn, service_name, project_id, service)\n  File \"/home/ubuntu/ansiblevenv/lib/python3.8/site-packages/otcextensions/sdk/__init__.py\", line 309, in register_single_service\n    sd = _get_descriptor(service_name)\n  File \"/home/ubuntu/ansiblevenv/lib/python3.8/site-packages/otcextensions/sdk/__init__.py\", line 189, in _get_descriptor\n    desc_class = _find_service_description_class(service_type)\n  File \"/home/ubuntu/ansiblevenv/lib/python3.8/site-packages/otcextensions/sdk/__init__.py\", line 234, in _find_service_description_class\n    service_description_module = importlib.import_module(import_name)\n  File \"/usr/lib/python3.8/importlib/__init__.py\", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 848, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/home/ubuntu/ansiblevenv/lib/python3.8/site-packages/otcextensions/sdk/elb/elb_service.py\", line 13, in <module>\n    from otcextensions.sdk.elb.v2 import _proxy as _proxy_v2\n  File \"/home/ubuntu/ansiblevenv/lib/python3.8/site-packages/otcextensions/sdk/elb/v2/_proxy.py\", line 16, in <module>\n    from otcextensions.sdk.elb.v2 import load_balancer as _load_balancer\n  File \"/home/ubuntu/ansiblevenv/lib/python3.8/site-packages/otcextensions/sdk/elb/v2/load_balancer.py\", line 14, in <module>\n    from openstack.common import tag\nModuleNotFoundError: No module named 'openstack.common'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

How can we fix this? Getting both things running, the native Ansible modules and the OTC modules?

Thanks for help and best Regards,
Martin

my playbook (following your example 1_initial_infra.yaml);

- name: Play 1 - Deploy on OTC 
  hosts: localhost
  gather_facts: false
  tasks:

  - name: Create ECS and attach it to the resources
    openstack.cloud.server:
      name: "test-1"
      image: "Standard_Ubuntu_20.04_latest"
      network: "<my VPC ID>"
      flavor: "s3.medium.1"
      availability_zone: "eu-de-01"
      volume_size: 6
      security_groups: default
      auto_ip: false
      state: present
    register: ecs
    tags:
      - server

**Comment by anton-sidelnikov** [comment]
@martpeli yes, for now please use 0.61.0 version, because for now we are waiting for release of openstack collection (which are using in a lot of resources) which will support newest versions of sdk

**Comment by martpeli** [comment]
@anton-sidelnikov 
thanks for the information, but how will I get the opentelekomcloud modules running?

especially I need a solution for the dns_recordset configuration:

- name: Play 1 - Deploy on OTC 
  hosts: localhost
  gather_facts: false
  vars:
    ecs_zone_id: 2c9c2dbb83ba143201845b99bac32113 
    
  tasks:
  # Creating / Updating a recordset:
  - name: opentelekomcloud.cloud.dns_recordset - Creating / Updating a recordset
    opentelekomcloud.cloud.dns_recordset:
      zone_id: "{{ ecs_zone_id }}"
      recordset_name: "myecs.mydomain.test"
      state: present
      ttl: 400
      type: A
      records:
        - "192.168.0.171"

**Comment by Polina-Gubina** [comment]
Hi Martin! did you install right version (pip install openstacksdk==0.61.0) inside virtualvenv or not? and  all other stuff?
No module named 'openstack.common' - this error can be caused installing it not in venv

**Comment by Polina-Gubina** [comment]
please try to use otcextensions version is  0.26.3

**Comment by martpeli** [comment]
Hello,

I've installed Ansible in a virtual environment following your installation guide:
https://github.com/opentelekomcloud/ansible-collection-cloud

The following changes got it to work (both, Ansible and OTC modules in one Playbook):
pip install openstacksdk==0.61.0
pip install otcextensions==0.26.3

Thanks for help :-)

best regards,
Martin

**Comment by Polina-Gubina** [comment]
cool news, Martin!
