### ISSUE TITLE
Looking for Module to set Bandwidth size/name and share type of floating IP

### ISSUE THREAD

**Issue by hadoopch** [opentelekomcloud/ansible-collection-cloud#250]
Hi all,

i am looking for a module which has the capability to set bandwith size, bandwidth name and share type.
The existing module floating_ip  does not have these options.

Maybe you can enhance the existing module.

Kind regards

Uli

**Comment by gtema** [comment]
floating_ip module will definitely not work for that, since bandwidth in OTC are not handeled as QoS in OpenStack and instead require invoking completely different apis. That means we are not able to extend floating_ip module of OpenStack.

**Comment by hadoopch** [comment]
Hi Artem,

then it would be great to have a new module which is able to do that.

If i use the REST-API i can  create a FIP and set the bandwidth at the same time

```
POST https://{Endpoint}/v1/{project_id}/publicips

{
    "publicip": {
        "type": "5_bgp",
        "ip_version": 4
    },
    "bandwidth": {
        "name": "bandwidth123",
        "size": 10,
        "share_type": "PER"
    },
    "enterprise_project_id":"b261ac1f-2489-4bc7-b31b-c33c3346a439"
```

You are right if i want adjust the Bandwith later i have to use a different URL.
```
PUT /v1/{project_id}/bandwidths/{bandwidth_id}
```

Regards

Uli

**Comment by gtema** [comment]
those apis are both non OpenStack ones. We take development of this module to the roadmap. Thanks

**Comment by hadoopch** [comment]
Thank you for your support.

**Comment by Polina-Gubina** [comment]
hi @hadoopch ! New modules were added: bandwidth and associate_bandwidth. With bandwidth you can create (assign), update and delete bandwidth and with associate_bandwidth you can assign eip to bandwidth or remove eip from bandwidth. Feel free to ask me questions if you have any
