### ISSUE TITLE
New Ansible collection for SWR service

### ISSUE THREAD

**Issue by oeotvos** [opentelekomcloud/ansible-collection-cloud#300]
This way I'd like to ask you for new ansible collection for SoftWare Repository for Containers (SWR).
https://docs.otc.t-systems.com/software-repository-container/api-ref/
https://github.com/opentelekomcloud-docs/software-repository-container/tree/main/api-ref/source

Please note, there is a difference between latest API ref version and previous (approved one).
CONT-1006

**Comment by anton-sidelnikov** [comment]
@RusselSand need to create two modules by each endpoint:

- [ ] swr_organication (create/update/delete)
- [ ] swr_organization_info (get/list)
- [ ] swr_repository  (create/update/delete)
- [ ] swr_repository_info (get/list)
- [ ] swr_domain  (create/update/delete)
- [ ] swr_domain_info (get/list)
