### ISSUE TITLE
DNS Zone is failing on updating

### ISSUE THREAD

**Issue by SebastianGode** [opentelekomcloud/ansible-collection-cloud#356]
This Apimon Test was disabled: https://github.com/opentelekomcloud-infra/apimon-tests/blob/master/playbooks/_scenario22a_simple_dns_private.yaml

The "Update private zone" part of DNS is not working. https://github.com/opentelekomcloud/ansible-collection-cloud/blob/main/plugins/modules/dns_zone.py -> If router parameter is not added, ansible dns module exits, but router is not a mandatory parameter for update operation.
![grafik](https://github.com/user-attachments/assets/fd5bfc6d-282c-49fb-871e-0958439d18bc)
![grafik](https://github.com/user-attachments/assets/5ed17fd2-f6fc-4bd6-af4f-55521c3533e5)

and it's running this part of the code while this is not creation, it should be update of the created private zone.

Also when running the code without changes it doesn't return "Ok" but an error.

**Comment by tischrei** [comment]
This issue is not valid. It seems that user is not using . at the end of the zone name.
