### ISSUE TITLE
LB Listener Info Example not functional

### ISSUE THREAD

**Issue by AdamVB** [opentelekomcloud/ansible-collection-cloud#90]
https://github.com/opentelekomcloud/ansible-collection-cloud/blob/9b4097726cd30a828650647013ad6b623d12671f/plugins/modules/lb_listener_info.py#L79

lb_listener_info does not take ```state``` as argument.

**Comment by AdamVB** [comment]
Same goes for: https://github.com/opentelekomcloud/ansible-collection-cloud/blob/9b4097726cd30a828650647013ad6b623d12671f/plugins/modules/lb_listener.py#L154

lb_listener module does not take ```loadbalancer_id``` but only ```loadbalancer``` argument

**Comment by anton-sidelnikov** [comment]
> Same goes for:
> 
> https://github.com/opentelekomcloud/ansible-collection-cloud/blob/9b4097726cd30a828650647013ad6b623d12671f/plugins/modules/lb_listener.py#L154
> 
> lb_listener module does not take `loadbalancer_id` but only `loadbalancer` argument

Yes, this is mistake in docu, lb_listener module in loadbalancer param can be name or id. Will fix it asap
