### ISSUE TITLE
Do not Hash a list

### ISSUE THREAD

**Issue by jackdown** [opentelekomcloud/ansible-collection-cloud#91]
Hi,

https://github.com/opentelekomcloud/ansible-collection-cloud/blob/9b4097726cd30a828650647013ad6b623d12671f/plugins/modules/lb_listener.py#L284

You can't hash a list of strings without explain python how to do that.

My solution would be, not to use hash and directly compare the lists.

```
 if sni_container_refs_filter and lb_listener.sni_container_refs != sni_container_refs_filter:
```

**Comment by jackdown** [comment]
Possible solution for: #90

**Comment by gtema** [comment]
@anton-sidelnikov, please have a look asap
